name: Update public-suffix-list.dat and rdap-servers-iana.json and icann-accredited-registrars.csv

on:
  schedule:
    - cron: "33 2 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: Fetch tags
        run: git fetch --tags

      - name: Download files
        run: |
          curl -fsSL "https://publicsuffix.org/list/public_suffix_list.dat" -o src/data/public-suffix-list.dat
          curl -fsSL "https://data.iana.org/rdap/dns.json" -o src/data/rdap-servers-iana.json
          curl -fsSL "https://www.icann.org/en/contracted-parties/accredited-registrars/list-of-accredited-registrars/csvdownload?sort-param=iana-number&sort-direction=asc" -o src/data/icann-accredited-registrars.csv

      - name: Commit and push
        run: |
          psl_updated=$(git diff --quiet src/data/public-suffix-list.dat; echo $?)
          rdap_updated=$(git diff --quiet src/data/rdap-servers-iana.json; echo $?)
          registrars_updated=$(git diff --quiet src/data/icann-accredited-registrars.csv; echo $?)

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          if [ $psl_updated -eq 1 ] || [ $rdap_updated -eq 1 ]; then
            base_tag="v$(date -u +%Y.%-m.%-d)"
            tag="${base_tag}"
            i=1
            while git rev-parse "${tag}" >/dev/null 2>&1; do
              tag="${base_tag}+${i}"
              ((i++))
            done

            sed -i "2s/.*/define(\"VERSION\", \"${tag}\");/" src/footer.php
            git add src/footer.php

            commit_message="Update version"
            if [ $psl_updated -eq 1 ]; then
              git add src/data/public-suffix-list.dat
              commit_message="${commit_message} and public-suffix-list.dat"
            fi
            if [ $rdap_updated -eq 1 ]; then
              git add src/data/rdap-servers-iana.json
              commit_message="${commit_message} and rdap-servers-iana.json"
            fi
            if [ $registrars_updated -eq 1 ]; then
              git add src/data/icann-accredited-registrars.csv
              commit_message="${commit_message} and icann-accredited-registrars.csv"
            fi

            git commit -m "${commit_message}"
            git push

            git tag "${tag}"
            git push origin "${tag}"
          elif [ $registrars_updated -eq 1 ]; then
            git add src/data/icann-accredited-registrars.csv
            git commit -m "Update icann-accredited-registrars.csv"
            git push
          else
            echo "No updates detected."
          fi
