name: Update public-suffix-list.dat and rdap-servers-iana.json

on:
  schedule:
    - cron: "33 2 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: Fetch tags
        run: git fetch --tags

      - name: Download files
        run: |
          curl -fsSL "https://publicsuffix.org/list/public_suffix_list.dat" -o src/data/public-suffix-list.dat
          curl -fsSL "https://data.iana.org/rdap/dns.json" -o src/data/rdap-servers-iana.json

      - name: Commit and push
        run: |
          psl_updated=$(git diff --quiet src/data/public-suffix-list.dat; echo $?)
          rdap_updated=$(git diff --quiet src/data/rdap-servers-iana.json; echo $?)

          if [[ $psl_updated == 1 || $rdap_updated == 1 ]]; then
            base_tag="v$(date -u +%Y.%-m.%-d)"
            tag="${base_tag}"
            i=1
            while git rev-parse "${tag}" >/dev/null 2>&1; do
              tag="${base_tag}+${i}"
              ((i++))
            done

            sed -i "5s/.*/define(\"VERSION\", \"${tag}\");/" config/config.php
            git add config/config.php

            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"

            commit_message=""

            if [[ $psl_updated == 1 ]]; then
              git add src/data/public-suffix-list.dat
              commit_message="public-suffix-list.dat"
            fi
            if [[ $rdap_updated == 1 ]]; then
              git add src/data/rdap-servers-iana.json
              if [[ -z $commit_message ]]; then
                commit_message="rdap-servers-iana.json"
              else
                commit_message="${commit_message} and rdap-servers-iana.json"
              fi
            fi

            commit_message="Update ${commit_message} and version"

            git commit -m "${commit_message}"
            git push

            git tag "${tag}"
            git push origin "${tag}"
          else
            echo "No updates detected."
          fi
